### PR TITLE
Added whitelisted exts for opus and yaml.

### PR DESCRIPTION
**Pull request by indrakaw**

### CODE REVIEW

**Comment by RX14** [comment]
Opus is fine, but we should check we serve the correct content security policy headers before whitelisting svg.

**Comment by clickbait** [comment]
i really don't want to whitelist svg

**Comment by indrakaw** [comment]
Remove: ~~Kebab~~ SVG. :ok_hand: 
Brb.

**Comment by indrakaw** [comment]
@rx14, @neko, is YAML ok?

Same as json, cvs, and xml. I need this for webapp.

**Comment by tn5421** [comment]
I gather that svg can't be allowed because it's behavior could be defined by an externally hosted xml file?

**Comment by RX14** [comment]
Svg is hard because it can contain javascript. That can be disabled by CSP headers though.

**Pull request merged**
